name: Nasm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up NASM
      uses: ilammy/setup-nasm@v1.0.0
      with:    
        version: 2.14.02
        platform: linux
    - name: make
      run: make:  
